with Internal.print

attempt = throw "Oh no!"

try attempt() catch(value) print(value)
